framework:
    messenger:
        failure_transport: failed

        transports:
            # Utilisation d'un transport en mémoire pour les tests
            async:
                dsn: 'in-memory://'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'in-memory://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
