controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_maj_facture_payer:
    path: /maj/facture/payer/{formId}
    controller: 'App\Controller\FactureController::marquerCommePayee'

app_maj_facture_non_payer:
    path: /maj/facture/non-payer/{formId}
    controller: 'App\Controller\FactureController::marquerCommeNonPayee'
